### ISSUE TITLE
Farmer Colonist can't plant berries

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Compat#1]
The farmer colonist does not seem to recognize how to plant berries.

Versions: 
- Minecolonies v1.0.1001-alpha
- https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3970866
  - The link has the required dependencies listed.

Steps:
1. Place a town hall block: https://wiki.minecolonies.ldtteam.com/source/buildings/townhall
  a. Follow instructions until "Creating your Colony" is finished.
2. Obtain a farmer's hut & place using the build tool: https://wiki.minecolonies.ldtteam.com/source/buildings/farm
  a. Right-click the build tool on the ground
  b. Choose the "medievalspruce" style, it contains a field
  ![image](https://user-images.githubusercontent.com/12000593/188680123-0e130d62-8ea6-4af4-8bcb-4b4d50eb8c49.png)  
  c. Click on the button circled in red to instantly paste the building into the world
  ![image](https://user-images.githubusercontent.com/12000593/188680789-092fc32f-a677-4ede-8ad4-b0b538696f56.png)
  d. The building should automatically "hire" a colonist
3. Right-click the scarecrow
![image](https://user-images.githubusercontent.com/12000593/188681291-249e9ebe-2636-4685-8907-edaad5a8792f.png)
4. Place a berry into the gui slot
5. Give a stack of berries & a stone hoe to the colonist
6. Wait to see if he/she plants any
7. If wheat seeds are placed in the scarecrow, the farmer usually starts planting right away.

**Comment by Thutmose** [comment]
this should be fixed now in pokecube 3.17.10+
